USE [lab5]
GO

CREATE TABLE Ta(
	aid INT PRIMARY KEY IDENTITY(1,1),
	a2 INT UNIQUE,
	a3 INT
)

CREATE TABLE Tb(
	bid INT PRIMARY KEY IDENTITY(1,1),
	b2 INT,
	b3 INT
)

CREATE TABLE Tc(
	cid INT PRIMARY KEY IDENTITY(1,1),
	aid INT,
	bid INT,
	FOREIGN KEY (aid) REFERENCES Ta(aid),
	FOREIGN KEY (bid) REFERENCES Tb(bid)
)

--A: CLUSTERED INDEX SCAN
SELECT * FROM Ta;

--CLUSTERED INDEX SEEK
SELECT * FROM Ta WHERE Ta.aid>100;

--NONCLUSTERED INDEX SCAN
SELECT Ta.a2 FROM Ta;

--NONCLUSTERED INDEX SEEK
SELECT Ta.a2 FROM Ta WHERE Ta.a2>100;

--KEY LOOKUP
SELECT * FROM Ta WHERE a2=100;

--B
SELECT b2 FROM Tb WHERE b2=100; --CLUSTERED INDEX SCAN

--DROP INDEX Table_B ON Tb;

CREATE INDEX Table_B
	ON Tb(b2);
SELECT b2 FROM Tb WHERE b2=100; --NONCLUSTERED INDEX SEEK

--C
CREATE OR ALTER VIEW ViewC AS
SELECT Tc.cid, Tb.bid FROM Tc 
INNER JOIN Tb ON Tc.bid=Tb.bid
GO

SELECT * FROM ViewC; --Tc: CLUSTERED INDEX SCAN
                     --Tb: CLUSTERED INDEX SEEK

CREATE INDEX Table_BC
	ON Tb(bid);

SELECT * FROM ViewC; --Tc: CLUSTERED INDEX SCAN
                     --Tb: NONCLUSTERED INDEX SEEK